### PR TITLE
vs 2019 build debug

### PR DESCRIPTION
**Pull request by Ian1971**

### CODE REVIEW

**Comment by danbrad** [comment]
@Ian1971 When I build your branch and install the extension in VS 2019 Pro, the menu item doesn't appear in the Tools menu. 

Did you have this problem?

**Comment by Ian1971** [comment]
I was really focused on getting it to build and unit tests to pass. See https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/issues/64

**Comment by danbrad** [comment]
Thanks. I was installing the version from the TargetFrameworkMigratorVSIX project. If I install the visx which is created in the TargetFrameworkMigrator project the menu item is there.

**Comment by Ian1971** [comment]
That's good. Does it also work?

**Comment by danbrad** [comment]
It worked all the way up until it had migrated all of the projects and then it died, taking visual studio with it.. 

Seems to have migrated the projects successfully though..

**Comment by Ian1971** [comment]
Close but no cigar

**Comment by 304NotModified** [comment]
@Ian1971 thanks for this PR, but I got it working after all. (green status master).

**Pull request closed without merging**
