### PR TITLE
Added .NET 4.7-4.8 and VS 2019 support

### LINKED ISSUE #38: Support for .net 4.7.1
I just stumbled upon this awesome tool, but I can't use it, because it lacks support for .Net 4.7.1. 
I would add it myself, but I don't see where you get _Id_ property from in your [framework definition](https://github.com/VHQLabs/TargetFrameworkMigrator/blob/master/TargetFrameworkMigrator/Frameworks.xml).

### LINKED ISSUE #49: Support .Net 4.7.2

### LINKED ISSUE #56: Support .NET 4.8
In order to add .NET 4.8, the Id 262152 should be added.
It looks like the ID can be generated by taking the version number, swap the last two parts, and convert from hex to dec, for example:
 
**Version: 2.0**
> **Hex** 02 00 00
> **Dec** 131072
 
**Version: 3.5**
> **Hex** 03 00 05
> **Dec** 196613
 
**Version: 4.0**
> **Hex** 04 00 00
> **Dec** 262144

**Version: 4.5**
> **Hex** 04 00 05
> **Dec** 262149
 
**Version: 4.5.1**
> **Hex** 04 01 05
> **Dec** 262405
 
**Version: 4.5.2**
> **Hex** 04 02 05
> **Dec** 262661
 
**Version: 4.6**
> **Hex** 04 00 06
> **Dec** 262150
 
**Version: 4.6.1**
> **Hex** 04 01 06
> **Dec** 262406
 
**Version: 4.6.2**
> **Hex** 04 02 06
> **Dec** 262662
 
**Version 4.7**
> **Hex** 04 00 07
> **Dec** 262151
 
**Version 4.7.1**
> **Hex** 04 01 07
> **Dec** 262407
 
**Version 4.7.2**
> **Hex** 04 02 07
> **Dec** 262663
 
**Version 4.8**
> **Hex** 04 00 08
> **Dec** 262152

### LINKED ISSUE #58: Doesn't install in Visual Studio 2019
Doesn't install in VS2019. Fails to install with the error saying references are missing to Microsoft.VisualStudio.Component.VSSDK. Visual Studio extension development workload is fully installed though.

### PR DESCRIPTION
**Pull request by Ian1971**
This was originally forked off of looselef/TargetFrameworkMigrator

Note that I have no idea what the magic numbers in frameworks.xml mean so I made up the 4.7.2 and 4.8 ones.

I also created a release https://github.com/Ian1971/TargetFrameworkMigrator/releases/tag/1.6.6 with the binary

fixes #58, fixes #56, fixes #49, fixes #38

### CODE REVIEW

**Comment by hybridview** [comment]
Installed perfectly in VS2019. Thanks Ian!

**Comment by DoomerDGR8** [comment]
Hi!

The numbers used in framework.xml for 4.7.2 and 4.8 are not correct. They should be 
262152 for 4.8 and 262663 4.7.2

**Comment by Ian1971** [comment]
> The numbers used in framework.xml for 4.7.2 and 4.8 are not correct. They should be
> 262152 for 4.8 and 262663 4.7.2
Out of interest where do these numbers come from, I couldn't work it out, hence them being wrong. I am not even sure what the consequence of them being wrong is, as it seems to work.

**Comment by Ian1971** [comment]
For future reference, this is shows how you can generate them. https://github.com/VHQLabs/TargetFrameworkMigrator/issues/56  I am not sure still what the significance is.

**Comment by Jogge** [comment]
> > The numbers used in framework.xml for 4.7.2 and 4.8 are not correct. They should be
> > 262152 for 4.8 and 262663 4.7.2
> 
> Out of interest where do these numbers come from, I couldn't work it out, hence them being wrong. I am not even sure what the consequence of them being wrong is, as it seems to work.

This article is the only thing i've found about these magic numbers: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vcprojectengine.enumframeworkversion

But I think @mastermattie is right here https://github.com/VHQLabs/TargetFrameworkMigrator/issues/56#issue-400190068:

> In order to add .NET 4.8, the Id 262152 should be added.
> It looks like the ID can be generated by taking the version number, swap the last two parts, and convert from hex to dec, for example:
> 
> **Version: 2.0**
> 
> > **Hex** 02 00 00
> > **Dec** 131072
> 
> **Version: 3.5**
> 
> > **Hex** 03 00 05
> > **Dec** 196613
> 
> **Version: 4.0**
> 
> > **Hex** 04 00 00
> > **Dec** 262144
> 
> **Version: 4.5**
> 
> > **Hex** 04 00 05
> > **Dec** 262149
> 
> **Version: 4.5.1**
> 
> > **Hex** 04 01 05
> > **Dec** 262405
> 
> **Version: 4.5.2**
> 
> > **Hex** 04 02 05
> > **Dec** 262661
> 
> **Version: 4.6**
> 
> > **Hex** 04 00 06
> > **Dec** 262150
> 
> **Version: 4.6.1**
> 
> > **Hex** 04 01 06
> > **Dec** 262406
> 
> **Version: 4.6.2**
> 
> > **Hex** 04 02 06
> > **Dec** 262662
> 
> **Version 4.7**
> 
> > **Hex** 04 00 07
> > **Dec** 262151
> 
> **Version 4.7.1**
> 
> > **Hex** 04 01 07
> > **Dec** 262407
> 
> **Version 4.7.2**
> 
> > **Hex** 04 02 07
> > **Dec** 262663
> 
> **Version 4.8**
> 
> > **Hex** 04 00 08
> > **Dec** 262152

**Comment by kendallb** [comment]
You should update the readme.md file to mention 4.8 support. Seems like the original maintainer who has access to publish this to the marketplace is no longer around?

**Comment by 304NotModified** [comment]
@vansickle could you please merge and release this? Thanks!

**Comment by 304NotModified** [comment]
Hi, I'm working on a Azure Devops pipleline. When that one is running, I will merge this one.

**Comment by 304NotModified** [comment]
@Ian1971  how do you got all the builds running? Which Visual Studio version did you use? Are the tests at your side green? 

PS: Have invited you to this repo so we could chat easier :)

**Comment by Ian1971** [comment]
> @Ian1971 how do you got all the builds running? Which Visual Studio version did you use? Are the tests at your side green?
It's a while and a whole new laptop since I tried to build it. So I think then I had vs 2017, and if I remember correctly the tests passed.
Now I have 2019.

**Pull request merged**
