### PR TITLE
Updated Migrator so that ArgumentExceptions checking the TargetFramew…

### PR DESCRIPTION
**Pull request by Edward84**
This catches an ArgumentException thrown when trying access the TargetFramework & TargetFrameworkMoniker on projects that don't contain the property, stopping the window from launching with the error "the parameter is incorrect. (Exception from HResult: 0x80070057 (E_INVALIDARG))"

It also updates the unit tests to run.

### CODE REVIEW

**Comment by ianwall** [comment]
Just came to report this problem and found your fix! Thanks.

**Comment by NetTecture** [comment]
Is there a chance this gets merged and then an update pushed to NuGet?

**Comment by Svenson77** [comment]
Same Problem here. My Workaround: I removed the setup project from solution and it works.

**Comment by 304NotModified** [comment]
Hi, 

Thanks for the code fix!

I'm working on a Azure Devops pipeline. When that one is running, I will probably merge this one.

**Pull request merged**
