### PR TITLE
Adding 4.7.1 (with version bump)

### PR DESCRIPTION
**Pull request by loosleef**
Took the commit for 4.7.1 from @STDGA and added version bump (& in README).

Tested with local solution at work with 40+ projects and successful upgrading 4.5.1 > 4.7.1

### CODE REVIEW

**Comment by ronwarner** [comment]
@loosleef  - I'd like to install your version of this VSIX for a quick 4.7.1 migration.  I have no idea how to compile this to something I can install as an extension.  Might you be able to point me in the right direction?  My searches aren't turning up much.

**Comment by tomekpr** [comment]
Hey guys, any chance this can be merged in ? We're migrating a lot of solutions to 471 and this extension would be a giant time saver.

**Comment by EasyAsABC123** [comment]
@tomekpr just pull latest and apply this patch, build and use?

**Comment by tomekpr** [comment]
Yeah that's what I've done. I wasn't sure how much hassle it will be with regards to vsix files but it wasn't a problem after all. Happy days

**Comment by ZukkyBaig** [comment]
Can someone merge this in?

**Comment by 304NotModified** [comment]
Thanks for the PR!

This will be fixed in the next release, probably by https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/pull/57

As this is an older PR, I will close this one instead of #57.

**Pull request closed without merging**
