### PR TITLE
Updated to support .NET Framework 4.7.2

### PR DESCRIPTION
**Pull request by travisterrell**
Added much needed support for 4.7.2. Even if it never gets merged, hopefully somebody will find my updated fork helpful.

### CODE REVIEW

**Comment by nicolas-boisseau** [comment]
Thank you for the 4.7.2 support :)

**Comment by SkylerJes** [comment]
Huzzah! I have dozens upon dozens of projects in my work environment and need 4.7.2 in particular. Thanks!

**Comment by xhevatibraimi** [comment]
> Added much needed support for 4.7.2. Even if it never gets merged, hopefully somebody will find my updated fork helpful.

I checked the differences in diffchecker, and it turns out that the only thing that you have done is removed trailing whitespaces, sorted the "using statements", and replaced 2 spaces indentation with 4 spaces indentation.

I did not encounter any code implementation change in any of 4 files that are updated.

image
image
image
image

**Comment by travisterrell** [comment]
There is info on how to update this package yourself if you look in the
Github comments. Just a couple lines.

Personally, wouldn't bother. I just use the "Find and Replace in Files"
feature of Sublime Text or Notepad++ to update your .csproj files. Much
much faster than this extension and just as easy.

**Comment by 304NotModified** [comment]
Thanks for the PR!

This will be fixed in the next release, probably by https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/pull/57

As this is an older PR, I will close this one instead of #57.

**Pull request closed without merging**
