### PR TITLE
Support for .NET 4.7.1 & 4.7.2 + version bump

### PR DESCRIPTION
**Pull request by FHannes**
I added the 4.7.1 and 4.7.2 frameworks to the list. Please publish vsix.

### CODE REVIEW

**Comment by pszittyay** [comment]
Please Merge

**Comment by hmvs** [comment]
Pity to see this not merged,

**Comment by kwende** [comment]
Why not just create a fork and someone else run with it? This guy is obviously AWOL. Their loss, but it doesn't have to be ours. Not like it's a complicated thing to write.

**Comment by Guson** [comment]
Plz: publish Hannes update.

**Comment by OFark** [comment]
In case of DIY, I found my files here: %LocalAppData%\Microsoft\VisualStudio\15.0_630ee505\Extensions\24n4fs45.ytv

**Comment by MatteoSp** [comment]
Please pull this

**Comment by jonranes** [comment]
Someone else took it up https://github.com/larbizard/TargetFrameworkMigrator-4.7.1  
VSIX is here https://larbigharib.com/index.php/2018/08/23/target-framework-migrator-4-7-1/

**Comment by Daxito** [comment]
Is there a VSIX for 4.7.2 anywhere?

**Comment by travisterrell** [comment]
No, but you can just grab this commit and compile it. Works fine.

(If I'm being honest though, it was quite slow on a 100+ project solution I
had to update. If your solution is very large, I'd recommend just using
Sublime Text/Notepad++ and do a "Find and Replace in Files" to bulk update
the version string in the .csproj files, which takes only a couple seconds.)

**Comment by Daxito** [comment]
Seems like it does work for VS 2017, well, I guess I will have to just Find and Replace then
......................................
1/27/2019 19:49:44 - InstallProgressPage ChangeType: 'SingleInstall' operationCount: '2' Text: 'Installing ...'
1/27/2019 19:49:44 - The following target products have been selected...
1/27/2019 19:49:44 - 	Visual Studio Professional 2017 (2)
1/27/2019 19:49:44 -

**Comment by randymarsh77** [comment]
FWIW: Using VS 15.9.8 (latest 2017 version at this time), I was able to:
- Clone the FHannes' fork of this repo
- Open and build the solution
- Double click the .vsix file in the bin directory to launch the extension installer
- Migrate projects to 4.7.2

Thanks for this!

**Comment by pnaszarkowski** [comment]
I'm getting an error after compilation and installation of the extension:
image

Anything I can do to make it work?
Thanks
Piotr

**Comment by pnaszarkowski** [comment]
The issue above was caused by the c++ project existing in the solution. Locally I added exclusion of this project type to the extension code and the error is gone, seems all is fine now.

**Comment by 304NotModified** [comment]
Thanks for the PR!

This will be fixed in the next release, probably by https://github.com/TargetFrameworkMigrator/TargetFrameworkMigrator/pull/57

As this is an older PR, I will close this one instead of #57.

**Pull request closed without merging**
